---
name: download bandwhich
run-name: download bandwhich-${{inputs.version}} from official release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version to build (without "v")
        default: 0.21.1
        type: string

permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin

    name: Download ${{matrix.target}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download
        run: |
          curl -sSLf -o bandwhich-v${{inputs.version}}-${{matrix.target}}.tar.gz "https://github.com/imsnif/bandwhich/releases/download/v${{inputs.version}}/bandwhich-v${{inputs.version}}-${{matrix.target}}.tar.gz"
      - name: Upload ${{matrix.target}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # create release if not exist
          gh release create "v${{inputs.version}}" --notes "Release bandwhich v${{inputs.version}}" --title "v${{inputs.version}}" --repo "${{github.repository}}" || true
          # delete the asset if exists
          gh release delete-asset "v${{inputs.version}}" "bandwhich-v${{inputs.version}}-${{matrix.target}}.tar.gz" --yes --repo "${{github.repository}}" || true
          gh release upload "v${{inputs.version}}" "./bandwhich-v${{inputs.version}}-${{matrix.target}}.tar.gz" --repo "${{github.repository}}"
